server:
  port: 4041
spring:
  application:
    name: harry-stream-input
  #Kafka
  kafka:
    bootstrap-servers: 192.168.234.134:9092
  #Rabbit Rabbit health check
  rabbitmq:
    addresses: 192.168.234.134:5672
  cloud:
    stream:
      bindings:
        harry_default_input:
          destination: harry_default
          group: harry_group_default