server:
  port: 4040
spring:
  application:
    name: harry-stream-output
  #Rabbit health check
  rabbitmq:
    addresses: 192.168.234.134:5672
  cloud:
    stream:
      bindings:
        harry_default_output:
          destination: harry_default
          group: harry_group_default
#          binder: rabbit_server
#      binders:
#        rabbit_server:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                addresses: 192.168.234.135:5672